# Generated by Django 5.2 on 2026-06-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('cart', '0002_alter_cart_user_alter_wishlist_user'),
        ('order', '0002_alter_order_user'),
        ('shop', '0002_alter_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
